---
# handlers file for vector-role
- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: false
    name: vector.service
    state: started
    
- name: Restart Vector
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted