---
- name: 'base packages'
  hosts: all
  become: true
  tags:
    - install

  tasks:
    - name: Installing tools
      apt:
        package: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - git
        - curl
        - wget
        - unzip
    - name: add ssh key
      ansible.builtin.authorized_key:
        user: vagrant
        state: present
        manage_dir: true
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
      become: true
      clickhouse_version: "22.4.6.53"

- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role
      vector_version: "0.30.0"

- name: Install lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role
