---
all:
  children:
    clickhouse:
      hosts:
        server.clickhouse.vagrant:
          ansible_host: 192.168.56.11
          ansible_connection: ssh
          ansible_user: vagrant
    lighthouse:
      hosts:
        server.lighthouse.vagrant:
          ansible_host: 192.168.56.13
          ansible_connection: ssh
          ansible_user: vagrant
    vector:
      hosts:
        server.vector.vagrant:
          ansible_host: 192.168.56.12
          ansible_connection: ssh
          ansible_user: vagrant
